parent:
  resistant:
    name: athlete
    R1: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_019_S1_L005_R1_001.fastq.gz
    R2: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_019_S1_L005_R2_001.fastq.gz
  susceptible:
    name: gemson
    R1: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_018_S1_L005_R1_001.fastq.gz
    R2: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_018_S1_L005_R2_001.fastq.gz
bulk:
  resistant:
    R1: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_020_S1_L005_R1_001.fastq.gz
    R2: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_020_S1_L005_R2_001.fastq.gz
  susceptible:
    R1: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_021_S1_L005_R1_001.fastq.gz
    R2: /mnt/shared/projects/jhi/potato/202201_RESAS_PCN/08022023_Arbor_RenSeq/9447-JK-6_021_S1_L005_R2_001.fastq.gz
reference:
  name: athlete_hifi
  fasta: /mnt/shared/scratch/tadams/smrtrenseq_assembly/assembly/Athlete/Athlete.contigs.fasta
bowtie2_args: "--score-min L,-0.18,-0.18 --phred33 --fr --maxins 1000 --very-sensitive --no-unal --no-discordant"
